CONSTRAINTS = ./constraints/ulx3s_v20_lvds.lpf

TOP_MODULE = ulx3s
TOP_MODULE_FILE = ..basic/ulx3s.vhd

VHDL_FILES = \
  $(TOP_MODULE_FILE) \
  ../scopeio/scopeio_top.vhd \
  ../scopeio/usbserial_rxd.vhd \
  ..basic/hdl/vga.vhd \
  ..basic/hdl/oled/oled_hex_decoder.vhd \
  ..basic/hdl/oled/oled_init_pack.vhd \
  ..basic/hdl/oled/oled_font_pack.vhd \
  ..basic/hdl/oled/vga/oled_vga.vhd \
  ..basic/hdl/oled/vga/oled_vga_init_pack.vhd \
  ..basic/hdl/spi_display/spi_display.vhd \
  ..basic/hdl/spi_display/spi_display_init_pack.vhd \
  ..basic/hdl/spi_display/st7789_init_pack.vhd \
  ..basic/hdl/spi_display/ssd1331_init_pack.vhd \
  ..basic/hdl/adc/max1112x_reader.vhd \
  ..basic/hdl/adc/max1112x_init_pack.vhd \


VHDL_LIB_NAME = hdl4fpga
VHDL_LIB_FILES = \
  ../../library/latticesemi/ecp5/ecp5pll.vhd \
  ../../librarybasic/align.vhd \
  ../../librarybasic/base.vhd \
  ../../librarybasic/bram.vhd \
  ../../librarybasic/dpram.vhd \
  ../../librarybasic/bram_true2p_2clk.vhd \
  ../../librarybasic/rom.vhd \
  ../../librarybasic/bcddiv2e.vhd \
  ../../librarybasic/vector.vhd \
  ../../librarybasic/dbdbbl.vhd \
  ../../librarybasic/stof.vhd \
  ../../librarybasic/dtos.vhd \
  ../../librarybasic/btod.vhd \
  ../../librarybasic/btof.vhd \
  ../../librarybasic/arbiter.vhd \
  ../../librarybasic/serdes.vhd \
  ../../librarybasic/fifo.vhd \
  ../../library/scope/scopeio.vhd \
  ../../library/scope/scopeiopkg.vhd \
  ../../library/scope/scopeio_capture.vhd \
  ../../library/scope/scopeio_capture1shot.vhd \
  ../../library/scope/scopeio_storage.vhd \
  ../../library/scope/scopeio_resize.vhd \
  ../../library/scope/scopeio_video.vhd \
  ../../library/scope/scopeio_textbox.vhd \
  ../../library/scope/scopeio_pointer.vhd \
  ../../library/sio/scopeio_rgtr2daisy.vhd \
  ../../library/sio/scopeio_istream.vhd \
  ../../library/sio/scopeio_istreamdaisy.vhd \
  ../../library/sio/scopeio_mouse2rgtr.vhd \
  ../../library/sio/scopeio_ps2mouse2daisy.vhd \
  ../../library/sio/scopeio_usbmouse2daisy.vhd \
  ../../library/sio/scopeio_hostmouse2daisy.vhd \
  ../../library/sio/scopeio_sin.vhd \
  ../../library/ps2mouse/mousem.vhd \
  ../../library/scope/scopeio_tds_1shot.vhd \
  ../../library/scope/scopeio_rgtrtrigger.vhd \
  ../../library/scope/scopeio_rgtrgain.vhd \
  ../../library/scope/scopeio_rgtrpointer.vhd \
  ../../library/scope/scopeio_rgtrvtaxis.vhd \
  ../../library/scope/scopeio_rgtrpalette.vhd \
  ../../library/scope/scopeio_rgtrhzaxis.vhd \
  ../../library/scope/scopeio_rgtrmyip.vhd \
  ../../library/scope/scopeio_amp.vhd \
  ../../library/scope/scopeio_downsampler.vhd \
  ../../library/scope/scopeio_grid.vhd \
  ../../library/scope/scopeio_palette.vhd \
  ../../library/scope/scopeio_segment.vhd \
  ../../library/scope/scopeio_tracer.vhd \
  ../../library/scope/scopeio_trigger.vhd \
  ../../library/scope/scopeio_axis.vhd \
  ../../library/scope/scopeio_btof.vhd \
  ../../library/scope/scopeio_float2btof.vhd \
  ../../library/scope/scopeio_layout.vhd \
  ../../library/scope/scopeio_textbox.vhd \
  ../../library/scope/textboxpkg.vhd \
  ../../library/uart/uart_rx.vhd \
  ../../library/uart/uart_rx_f32c.vhd \
  ../../library/mii/ethpkg.vhd \
  ../../library/mii/ipoepkg.vhd \
  ../../library/mii/mii_1chksum.vhd \
  ../../library/mii/mii_cmp.vhd \
  ../../library/mii/mii_ram.vhd \
  ../../library/mii/mii_rom.vhd \
  ../../library/mii/mii_romcmp.vhd \
  ../../library/mii/mii_rxpre.vhd \
  ../../library/mii/mii_muxcmp.vhd \
  ../../library/mii/mii_ipoe.vhd \
  ../../library/mii/mii_mux.vhd \
  ../../library/mii/mii_des.vhd \
  ../../library/mii/mii_latency.vhd \
  ../../library/mii/mii_debug.vhd \
  ../../library/mii/mii_display.vhd \
  ../../library/mii/eth_tx.vhd \
  ../../library/mii/eth_rx.vhd \
  ../../library/mii/eth_dll.vhd \
  ../../library/mii/eth_crc32.vhd \
  ../../library/mii/arp_tx.vhd \
  ../../library/mii/arp_rx.vhd \
  ../../library/mii/ipv4_tx.vhd \
  ../../library/mii/ipv4_rx.vhd \
  ../../library/mii/icmprqst_rx.vhd \
  ../../library/mii/icmprply_tx.vhd \
  ../../library/mii/dhcp_dscb.vhd \
  ../../library/mii/dhcp_offer.vhd \
  ../../library/mii/udp_tx.vhd \
  ../../library/mii/udp_rx.vhd \
  ../../library/usb/usbcdc/usb_serial.vhd \
  ../../library/usb/usbcdc/usb_mii.vhd \
  ../../library/usb/usbcdc/usb_cdc_descriptor_pack.vhd \
  ../../library/usb/usbcdc/usb_transact.vhd \
  ../../library/usb/usbcdc/usb_packet.vhd \
  ../../library/usb/usbcdc/usb_init.vhd \
  ../../library/usb/usbcdc/usb_control.vhd \
  ../../library/usb/usbhost/usbh_host_hid.vhd \
  ../../library/usb/usbhost/usbh_setup_pack.vhd \
  ../../library/usb/usbhost/usbh_report_decoder_logitech_mouse.vhd \
  ../../library/usb/usbhost/usbh_sie_vhdl.vhd \
  ../../library/usb/usb11_phy_vhdl/usb_phy_transciver.vhd \
  ../../library/usb/usb11_phy_vhdl/usb_phy.vhd \
  ../../library/usb/usb11_phy_vhdl/usb_rx_phy_48MHz.vhd \
  ../../library/usb/usb11_phy_vhdl/usb_rx_phy_emard.vhd \
  ../../library/usb/usb11_phy_vhdl/usb_tx_phy.vhd \
  ../../library/usb/ulpi_wrapper/ulpi_wrapper_vhdl.vhd \
  ../../library/video/video.vhd \
  ../../library/video/videopkg.vhd \
  ../../library/video/modeline_calculator.vhd \
  ../../library/video/cgafonts.vhd \
  ../../library/video/fonts/cp850x8x16x0to127.vhd \
  ../../library/video/fonts/cp850x8x16x128to255.vhd \
  ../../library/video/fonts/cp850x8x8x0to127.vhd \
  ../../library/video/fonts/cp850x8x8x128to255.vhd \
  ../../library/video/fonts/bcdfonts.vhd \
  ../../library/video/cga_rom.vhd \
  ../../library/video/vga2dvid.vhd \
  ../../library/video/tmds_encoder.vhd \
  ../../library/video/vga2lvds.vhd \
  ../../library/video/lvds2vga.vhd \
  ../../library/video/cga_adapter.vhd \

VERILOG_FILES = \
  ../../library/usb/usbhost/usbh_sie.v \
  ../../library/usb/usbhost/usbh_crc5.v \
  ../../library/usb/usbhost/usbh_crc16.v \
  ../../library/usb/ulpi_wrapper/ulpi_wrapper.v \

#  ../../library/sio/scopeio_udpipdaisy.vhd \
