graphics: apps.ldf
	echo prj_project open apps.ldf \; prj_run Export -impl graphics -task Bitgen | diamondc

clean: 
	rm -rf graphics eth_tb graphics hdlc_debug ser_debug apps_tcl.html promote.xml reportview.xml

.PHONY: graphics clean
